name: Generate Podcast Feeds
on: [push] # Whenever someone pushes into the branch (main)
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3 # An action in the marketplace called Checkout, using version 3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run:  |
          python -m pip install --upgrade pip
          pip install pyyaml
      - name: Run Feed Generator
        run: python feed.py
      - name: Push Repo
        run: | # This is creating a new machine to run the action, need to set up Git for that
          git config user.name StoneTD
          git config user.email dylanstone0147@gmail.com
          git add .
          git commit -m "Modified Feed via GitHub Action"
          git push
        
