name: Generate Podcast Feeds
on: [push] # Whenever someone pushes onto the branch (main)
jobs:
  build:
    runs-on: ubuntu-latest  # Creates a new machine, can be Windows but why
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3  # An action in the marketplace called Checkout, using version 3
        
      - name: Run Feed Generator
        uses: StoneTD/generation-testing@main  # A custom made action in my repository, using main branch
